--- #YAML:1.0
name:                HTTP-DAV
version:             0.33
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    LWP:                           5.48
    Scalar::Util:                  0
    XML::DOM:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
